from datetime import date
from flask_bcrypt import Bcrypt
from models import User, Subject, Chapter, Quiz, Question, Score, Admin
bcrypt = Bcrypt()

users = [
    User(
        username="gauri03",
        password=bcrypt.generate_password_hash("gauri123").decode("utf-8"),
        dob=date(2003, 1, 1),
        qualification="B.E. Computer Science",
    ),
    User(
        username="anaya04",
        password=bcrypt.generate_password_hash("anaya123").decode("utf-8"),
        dob=date(2004, 2, 2),
        qualification="B.Tech. Information Science",
    ),
    User(
        username="siddhi05",
        password=bcrypt.generate_password_hash("siddhi123").decode("utf-8"),
        dob=date(2005, 3, 3),
        qualification="B.Sc. Computer Science",
    ),
    User(
        username="rahul06",
        password=bcrypt.generate_password_hash("rahul123").decode("utf-8"),
        dob=date(2003, 4, 4),
        qualification="B.E. Information Technology",
    ),
    User(
        username="neha07",
        password=bcrypt.generate_password_hash("neha123").decode("utf-8"),
        dob=date(2002, 5, 5),
        qualification="B.Tech. Computer Science",
    ),
    User(
        username="arjun08",
        password=bcrypt.generate_password_hash("arjun123").decode("utf-8"),
        dob=date(2004, 6, 6),
        qualification="B.E. Computer Science",
    ),
    User(
        username="isha09",
        password=bcrypt.generate_password_hash("isha123").decode("utf-8"),
        dob=date(2003, 7, 7),
        qualification="B.Sc. Information Technology",
    ),
    User(
        username="kiran10",
        password=bcrypt.generate_password_hash("kiran123").decode("utf-8"),
        dob=date(2002, 8, 8),
        qualification="B.Tech. Data Science",
    ),
    User(
        username="priya11",
        password=bcrypt.generate_password_hash("priya123").decode("utf-8"),
        dob=date(2005, 9, 9),
        qualification="B.E. Data Science",
    ),
    User(
        username="omkar12",
        password=bcrypt.generate_password_hash("omkar123").decode("utf-8"),
        dob=date(2001, 10, 10),
        qualification="B.Sc. Computer Applications",
    ),
]

subjects = [
    Subject(name="Modern Application Development", description="Covers scalable, cloud-native, and user-centric apps."),
    Subject(name="Business Data Management and Specification", description="Focuses on collecting, storing, processing, and analyzing data."),
    Subject(name="Programming Data Structures and Algorithms", description="Designing efficient solutions using DSA."),
    Subject(name="Business Analytics", description="Use of data, stats, and ML to analyze performance."),
    Subject(name="Machine Learning Foundations", description="Core ML concepts and intuition."),
    Subject(name="Machine Learning Techniques", description="Advanced algorithms and models."),
]

chapters = [
    Chapter(subject_id=1, name="Introduction to Modern Application Development", description="Overview of modern application development."),
    Chapter(subject_id=1, name="Cloud-Native Applications", description="Building applications for the cloud."),
    Chapter(subject_id=1, name="User-Centric Design", description="Designing applications with the user in mind."),
    Chapter(subject_id=1, name="Scalability and Performance", description="Ensuring applications can scale."),
    Chapter(subject_id=2, name="Data Collection", description="Methods for collecting data."),
    Chapter(subject_id=2, name="Data Storage", description="Storing data efficiently."),
    Chapter(subject_id=2, name="Data Processing", description="Processing data for analysis."),
    Chapter(subject_id=2, name="Data Analysis", description="Analyzing data for insights."),
    Chapter(subject_id=3, name="Introduction to Data Structures", description="Basics of data structures."),
    Chapter(subject_id=3, name="Algorithms", description="Understanding algorithms."),
    Chapter(subject_id=3, name="Complexity Analysis", description="Analyzing algorithm efficiency."),
    Chapter(subject_id=3, name="Advanced Data Structures", description="Exploring advanced data structures."),
    Chapter(subject_id=4, name="Introduction to Business Analytics", description="Basics of business analytics."),
    Chapter(subject_id=4, name="Statistical Analysis", description="Using statistics for analysis."),
    Chapter(subject_id=4, name="Machine Learning Basics", description="Introduction to machine learning."),
    Chapter(subject_id=4, name="Data Visualization", description="Visualizing data for insights."),
    Chapter(subject_id=5, name="Introduction to Machine Learning", description="Basics of machine learning."),
    Chapter(subject_id=5, name="Supervised Learning", description="Understanding supervised learning."),
    Chapter(subject_id=5, name="Unsupervised Learning", description="Understanding unsupervised learning."),
    Chapter(subject_id=5, name="Reinforcement Learning", description="Basics of reinforcement learning."),
    Chapter(subject_id=6, name="Regression Techniques", description="Understanding regression techniques."),
    Chapter(subject_id=6, name="Classification Techniques", description="Understanding classification techniques."),
    Chapter(subject_id=6, name="Clustering Techniques", description="Understanding clustering techniques."),
    Chapter(subject_id=6, name="Neural Networks", description="Basics of neural networks."),
]

quizzes = [
    Quiz(chapter_id=1, name="Quiz 1", description="Quiz on Introduction to Modern Application Development"),
    Quiz(chapter_id=2, name="Quiz 2", description="Quiz on Cloud-Native Applications"),
    Quiz(chapter_id=3, name="Quiz 3", description="Quiz on User-Centric Design"),
    Quiz(chapter_id=4, name="Quiz 4", description="Quiz on Scalability and Performance"),
    Quiz(chapter_id=5, name="Quiz 5", description="Quiz on Data Collection"),
    Quiz(chapter_id=6, name="Quiz 6", description="Quiz on Data Storage"),
    Quiz(chapter_id=7, name="Quiz 7", description="Quiz on Data Processing"),
    Quiz(chapter_id=8, name="Quiz 8", description="Quiz on Data Analysis"),
    Quiz(chapter_id=9, name="Quiz 9", description="Quiz on Introduction to Data Structures"),
    Quiz(chapter_id=10, name="Quiz 10", description="Quiz on Algorithms"),
    Quiz(chapter_id=11, name="Quiz 11", description="Quiz on Complexity Analysis"),
    Quiz(chapter_id=12, name="Quiz 12", description="Quiz on Advanced Data Structures"),
    Quiz(chapter_id=13, name="Quiz 13", description="Quiz on Introduction to Business Analytics"),
    Quiz(chapter_id=14, name="Quiz 14", description="Quiz on Statistical Analysis"),
    Quiz(chapter_id=15, name="Quiz 15", description="Quiz on Machine Learning Basics"),
    Quiz(chapter_id=16, name="Quiz 16", description="Quiz on Data Visualization"),
    Quiz(chapter_id=17, name="Quiz 17", description="Quiz on Introduction to Machine Learning"),
    Quiz(chapter_id=18, name="Quiz 18", description="Quiz on Supervised Learning"),
    Quiz(chapter_id=19, name="Quiz 19", description="Quiz on Unsupervised Learning"),
    Quiz(chapter_id=20, name="Quiz 20", description="Quiz on Reinforcement Learning"),
    Quiz(chapter_id=21, name="Quiz 21", description="Quiz on Regression Techniques"),
    Quiz(chapter_id=22, name="Quiz 22", description="Quiz on Classification Techniques"),
    Quiz(chapter_id=23, name="Quiz 23", description="Quiz on Clustering Techniques"),
    Quiz(chapter_id=24, name="Quiz 24", description="Quiz on Neural Networks"),
]

questions = [
    Question(quiz_id=1, statement="What is the primary focus of modern application development?", option_a="User experience", option_b="Data storage", option_c="Cloud computing", option_d="All of the above", correct_answer="All of the above"),
    Question(quiz_id=1, statement="Which of the following is NOT a characteristic of cloud-native applications?", option_a="Scalability", option_b="Portability", option_c="Monolithic architecture", option_d="Microservices architecture", correct_answer="Monolithic architecture"),
    Question(quiz_id=1, statement="What is the main advantage of user-centric design?", option_a="Faster development", option_b="Improved user satisfaction", option_c="Lower costs", option_d="Easier maintenance", correct_answer="Improved user satisfaction"),
    Question(quiz_id=1, statement="Which of the following is a key principle of scalability?", option_a="Vertical scaling", option_b="Horizontal scaling", option_c="Both A and B", option_d="None of the above", correct_answer="Both A and B"),
    Question(quiz_id=2, statement="What is the primary purpose of data collection?", option_a="Data storage", option_b="Data analysis", option_c="Data visualization", option_d="Data processing", correct_answer="Data storage"),
    Question(quiz_id=2, statement="Which of the following is NOT a method of data collection?", option_a="Surveys", option_b="Interviews", option_c="Data mining", option_d="Data analysis", correct_answer="Data analysis"),
    Question(quiz_id=2, statement="What is the main advantage of using databases for data storage?", option_a="Data redundancy", option_b="Data integrity", option_c="Data inconsistency", option_d="Data loss", correct_answer="Data integrity"),
    Question(quiz_id=2, statement="Which of the following is a common data processing technique?", option_a="Data cleaning", option_b="Data visualization", option_c="Data analysis", option_d="All of the above", correct_answer="All of the above"),
    Question(quiz_id=3, statement="What is the primary goal of data analysis?", option_a="Data collection", option_b="Data storage", option_c="Data interpretation", option_d="Data processing", correct_answer="Data interpretation"),
    Question(quiz_id=3, statement="Which of the following is NOT a type of data analysis?", option_a="Descriptive analysis", option_b="Predictive analysis", option_c="Prescriptive analysis", option_d="Data mining", correct_answer="Data mining"),
    Question(quiz_id=3, statement="What is the main advantage of using statistical methods for data analysis?", option_a="Data redundancy", option_b="Data integrity", option_c="Data consistency", option_d="Data interpretation", correct_answer="Data interpretation"),
    Question(quiz_id=3, statement="Which of the following is a common data visualization technique?", option_a="Bar charts", option_b="Pie charts", option_c="Line graphs", option_d="All of the above", correct_answer="All of the above"),
    Question(quiz_id=4, statement="What is the primary focus of data structures?", option_a="Data storage", option_b="Data processing", option_c="Data analysis", option_d="Data visualization", correct_answer="Data storage"),
    Question(quiz_id=4, statement="Which of the following is NOT a type of data structure?", option_a="Array", option_b="Linked list", option_c="Database", option_d="Tree", correct_answer="Database"),
    Question(quiz_id=4, statement="What is the main advantage of using algorithms?", option_a="Data redundancy", option_b="Data integrity", option_c="Data consistency", option_d="Efficient problem solving", correct_answer="Efficient problem solving"),
    Question(quiz_id=4, statement="Which of the following is a common algorithm design technique?", option_a="Divide and conquer", option_b="Greedy method", option_c="Dynamic programming", option_d="All of the above", correct_answer="All of the above"),    
    Question(quiz_id=5, statement="What is the primary goal of business analytics?", option_a="Data collection", option_b="Data storage", option_c="Data analysis", option_d="Data visualization", correct_answer="Data analysis"),
    Question(quiz_id=5, statement="Which of the following is NOT a type of business analytics?", option_a="Descriptive analytics", option_b="Predictive analytics", option_c="Prescriptive analytics", option_d="Data mining", correct_answer="Data mining"),   
    Question(quiz_id=5, statement="What is the main advantage of using statistical methods for business analytics?", option_a="Data redundancy", option_b="Data integrity", option_c="Data consistency", option_d="Data interpretation", correct_answer="Data interpretation"),
    Question(quiz_id=5, statement="Which of the following is a common data visualization technique?", option_a="Bar charts", option_b="Pie charts", option_c="Line graphs", option_d="All of the above", correct_answer="All of the above"),
    Question(quiz_id=6, statement="What is the primary focus of machine learning?", option_a="Data collection", option_b="Data storage", option_c="Data analysis", option_d="Data prediction", correct_answer="Data prediction"),
    Question(quiz_id=6, statement="Which of the following is NOT a type of machine learning?", option_a="Supervised learning", option_b="Unsupervised learning", option_c="Reinforcement learning", option_d="Data mining", correct_answer="Data mining"),
    Question(quiz_id=6, statement="What is the main advantage of using machine learning?", option_a="Data redundancy", option_b="Data integrity", option_c="Data consistency", option_d="Automated decision making", correct_answer="Automated decision making"),
    Question(quiz_id=6, statement="Which of the following is a common machine learning algorithm?", option_a="Linear regression", option_b="Decision trees", option_c="Neural networks", option_d="All of the above", correct_answer="All of the above"),
    Question(quiz_id=7, statement="What is the primary focus of machine learning techniques?", option_a="Data collection", option_b="Data storage", option_c="Data analysis", option_d="Data prediction", correct_answer="Data prediction"),
    Question(quiz_id=7, statement="Which of the following is NOT a type of machine learning technique?", option_a="Regression", option_b="Classification", option_c="Clustering", option_d="Data mining", correct_answer="Data mining"),
    Question(quiz_id=7, statement="What is the main advantage of using machine learning techniques?", option_a="Data redundancy", option_b="Data integrity", option_c="Data consistency", option_d="Automated decision making", correct_answer="Automated decision making"),
    Question(quiz_id=7, statement="Which of the following is a common machine learning technique?", option_a="Linear regression", option_b="Decision trees", option_c="Neural networks", option_d="All of the above", correct_answer="All of the above"),
    Question(quiz_id=8, statement="What is the primary focus of machine learning foundations?", option_a="Data collection", option_b="Data storage", option_c="Data analysis", option_d="Data prediction", correct_answer="Data prediction"),
    Question(quiz_id=8, statement="Which of the following is NOT a type of machine learning foundation?", option_a="Regression", option_b="Classification", option_c="Clustering", option_d="Data mining", correct_answer="Data mining"),
    Question(quiz_id=8, statement="What is the main advantage of using machine learning foundations?", option_a="Data redundancy", option_b="Data integrity", option_c="Data consistency", option_d="Automated decision making", correct_answer="Automated decision making"),
    Question(quiz_id=8, statement="Which of the following is a common machine learning foundation?", option_a="Linear regression", option_b="Decision trees", option_c="Neural networks", option_d="All of the above", correct_answer="All of the above"),
    Question(quiz_id=9, statement="What is the primary focus of machine learning techniques?", option_a="Data collection", option_b="Data storage", option_c="Data analysis", option_d="Data prediction", correct_answer="Data prediction"),
    Question(quiz_id=9, statement="Which of the following is NOT a type of machine learning technique?", option_a="Regression", option_b="Classification", option_c="Clustering", option_d="Data mining", correct_answer="Data mining"),
    Question(quiz_id=9, statement="What is the main advantage of using machine learning techniques?", option_a="Data redundancy", option_b="Data integrity", option_c="Data consistency", option_d="Automated decision making", correct_answer="Automated decision making"),
    Question(quiz_id=9, statement="Which of the following is a common machine learning technique?", option_a="Linear regression", option_b="Decision trees", option_c="Neural networks", option_d="All of the above", correct_answer="All of the above"),
    Question(quiz_id=10, statement="What is the primary focus of machine learning foundations?", option_a="Data collection", option_b="Data storage", option_c="Data analysis", option_d="Data prediction", correct_answer="Data prediction"),
    Question(quiz_id=10, statement="Which of the following is NOT a type of machine learning foundation?", option_a="Regression", option_b="Classification", option_c="Clustering", option_d="Data mining", correct_answer="Data mining"),
    Question(quiz_id=10, statement="What is the main advantage of using machine learning foundations?", option_a="Data redundancy", option_b="Data integrity", option_c="Data consistency", option_d="Automated decision making", correct_answer="Automated decision making"),
    Question(quiz_id=10, statement="Which of the following is a common machine learning foundation?", option_a="Linear regression", option_b="Decision trees", option_c="Neural networks", option_d="All of the above", correct_answer="All of the above"),
    Question(quiz_id=11, statement="What is the primary focus of machine learning techniques?", option_a="Data collection", option_b="Data storage", option_c="Data analysis", option_d="Data prediction", correct_answer="Data prediction"),
    Question(quiz_id=11, statement="Which of the following is NOT a type of machine learning technique?", option_a="Regression", option_b="Classification", option_c="Clustering", option_d="Data mining", correct_answer="Data mining"),
    Question(quiz_id=11, statement="What is the main advantage of using machine learning techniques?", option_a="Data redundancy", option_b="Data integrity", option_c="Data consistency", option_d="Automated decision making", correct_answer="Automated decision making"),
    Question(quiz_id=11, statement="Which of the following is a common machine learning technique?", option_a="Linear regression", option_b="Decision trees", option_c="Neural networks", option_d="All of the above", correct_answer="All of the above"),
    Question(quiz_id=12, statement="What is the primary focus of machine learning foundations?", option_a="Data collection", option_b="Data storage", option_c="Data analysis", option_d="Data prediction", correct_answer="Data prediction"),
    Question(quiz_id=12, statement="Which of the following is NOT a type of machine learning foundation?", option_a="Regression", option_b="Classification", option_c="Clustering", option_d="Data mining", correct_answer="Data mining"),
    Question(quiz_id=12, statement="What is the main advantage of using machine learning foundations?", option_a="Data redundancy", option_b="Data integrity", option_c="Data consistency", option_d="Automated decision making", correct_answer="Automated decision making"),
    Question(quiz_id=12, statement="Which of the following is a common machine learning foundation?", option_a="Linear regression", option_b="Decision trees", option_c="Neural networks", option_d="All of the above", correct_answer="All of the above"),
    Question(quiz_id=13, statement="What is the primary focus of machine learning techniques?", option_a="Data collection", option_b="Data storage", option_c="Data analysis", option_d="Data prediction", correct_answer="Data prediction"),
    Question(quiz_id=13, statement="Which of the following is NOT a type of machine learning technique?", option_a="Regression", option_b="Classification", option_c="Clustering", option_d="Data mining", correct_answer="Data mining"),
    Question(quiz_id=13, statement="What is the main advantage of using machine learning techniques?", option_a="Data redundancy", option_b="Data integrity", option_c="Data consistency", option_d="Automated decision making", correct_answer="Automated decision making"),
    Question(quiz_id=13, statement="Which of the following is a common machine learning technique?", option_a="Linear regression", option_b="Decision trees", option_c="Neural networks", option_d="All of the above", correct_answer="All of the above"),
    
]